services:
    wordpress:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db:/var/lib/postgresql/data
