services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${PGDATABASE}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
        volumes:
            - ./db/postgres:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=dlrivada@hotmail.com
            - PGADMIN_DEFAULT_PASSWORD=thingst
        ports:
            - "5050:80"
        restart: always
    mysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${MYSQLDATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
            MYSQL_USER: ${MYSQLUSER}
            MYSQL_PASSWORD: ${MYSQLPASSWORD}
        volumes:
            - ./db/mysql:/var/lib/mysql
