services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - ${DB_PORT}:5432
        expose:
            - '5432'
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./docker:/var/lib/postgresql/data
